config/routes.rb
Rails.application.routes.draw do
  

  
  root to: 'welcome#home'
  resources :topics, except: [:new, :edit, :update] do
    resources :bookmarks, only: [:destroy]
  end
  resources :bookmarks, only: [] do
    resources :likes, only: [:create, :destroy]
  end
  post :incoming, to: 'incoming#create'
  devise_for :users
  resources :users, only: [:show]
  

end

app/models/bookmark.rb
class Bookmark < ActiveRecord::Base
  belongs_to :topic
  belongs_to :user
  has_many :likes, dependent: :destroy
end

app/models/like.rb
class Like < ActiveRecord::Base
  belongs_to :bookmark
  belongs_to :user
end

app/models/topic.rb
class Topic < ActiveRecord::Base
  
  extend FriendlyId
  friendly_id :title, use: [:slugged, :history]
  
  belongs_to :user
  has_many :bookmarks
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable
         
  extend FriendlyId
  friendly_id :user_name, use: [:slugged, :history]
  
  has_many :topics
  has_many :bookmarks
  has_many :likes, dependent: :destroy
  
  
  def liked(bookmark)
    likes.where(bookmark_id: bookmark.id).first
  end
  
  def liked_bookmarks
    bookmarks = []
    likes.each {|like| bookmarks << Bookmark.find(like.bookmark_id) }
    bookmarks
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  include Pundit
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?
  
  
  protected
  
  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :user_name
    devise_parameter_sanitizer.for(:account_update) << :user_name
  end
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController

  def destroy
    @bookmark = Bookmark.find(params[:id])
    authorize @bookmark
    if @bookmark.destroy
      flash[:notice] = "Bookmark was deleted"
    else
      flash[:error] = "Bookmark could not be deleted"
    end
    redirect_to :back
  end

  
end

app/controllers/incoming_controller.rb
class IncomingController < ApplicationController
    
    skip_before_action :verify_authenticity_token, only: [:create]
    
    def create
        user = User.find_by(email: params[:sender])
        if user
            topic = Topic.find_by(title: params[:subject])
            topic = Topic.create(title: params[:subject], user: user) unless topic
            url = params["body-plain"]
            Bookmark.create(url: url, topic: topic)
        end
        head 200
    end
    
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    @bookmark = Bookmark.find(params[:bookmark_id])
    @like = current_user.likes.build(bookmark: @bookmark)
    authorize @like
    if @like.save
      flash.now[:notice] = "Bookmark liked"   
    else
      flash.now[:error] = "Bookmark could not be liked, try again later"
    end
    
    respond_to do |format|
      format.js
      format.html
    end
  end
    
  def destroy
    @bookmark = Bookmark.find(params[:bookmark_id])
    @like = Like.find_by(user_id: current_user.id, bookmark_id: @bookmark.id)
    authorize @like
    if @like.destroy
      flash.now[:notice] = "Bookmark unliked"
    else
      flash.now[:error] = "Bookmark could not be unliked, try again later"
    end
    respond_to do |format|
      format.js
      format.html
    end
  end
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  def index
    @topics = Topic.all
  end

  def show
    @topic = Topic.friendly.find(params[:id])
  end

  
  def create
    @topic = current_user.topics.new(topic_params)
    @new_topic = Topic.new
    authorize @topic
    if @topic.save
      flash.now[:notice] = "Topic created successfully."
    else
      flash.now[:error] = "Topic could not be created."
    end
    
    respond_to do |format|
      format.html
      format.js
    end
  end
  
  def destroy
    @topic = Topic.friendly.find(params[:id])
    authorize @topic
    if @topic.destroy
      flash.now[:notice] = "Topic was deleted."
    else
      flash.now[:error] = "Topic could not be deleted."
    end
    respond_to do |format|
      format.html
      format.js
    end
  end
  
  
  private
  
  def topic_params
    params.require(:topic).permit(:title)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.friendly.find(params[:id])

    @user_bookmarks = @user.bookmarks.group_by(&:topic)
    @liked_bookmarks = @user.liked_bookmarks.group_by(&:topic)
    
    if request.path != user_path(@user)
      redirect_to @user, status: :moved_permanently
    end
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

    def url_with_protocol(url)
      /^http/i.match(url) ? url : "http://#{url}"
    end
    
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/helpers/users_helper.rb
module UsersHelper
    
  def show_name(user)
    user == current_user ? 'My ' : "#{user.user_name}'s "
  end
    
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/bookmarks/_bookmark.html.erb
<%= content_tag :div, class: "col-md-4", id: bookmark.id do %>
    <a class="embedly-card" data-card-theme="light" data-card-chrome="0" data-card-controls="0" href=<%= url_with_protocol(bookmark.url) %>></a>
    <%= render partial: 'likes/like', locals: { bookmark: bookmark } %>
    <% if policy(bookmark).destroy? %>
        <%= link_to [bookmark.topic, bookmark], class: 'btn btn-danger', method: :delete, title: "Delete bookmark", data: {confirm: "Do you want to delete this bookmark?"} do %>
            <i class="glyphicon glyphicon-remove"></i>&nbsp; Delete
        <% end %>
    <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blocmarks</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <div class="container">
      <ul class="nav nav-tabs">
        <div class="pull-left">
          <% if user_signed_in? %>
            <%= link_to "Home", topics_path, class: 'navbar-link' %>
          <% end %>
        </div>
        <div class="pull-right">
          <% if user_signed_in? %>
            Signed in as: <strong><%= link_to current_user.user_name, user_path(current_user.id), class:'navbar-link' %></strong> |
            <%= link_to 'Edit profile', edit_user_registration_path, class: 'navbar-link' %> - <%= link_to "Sign out", destroy_user_session_path, method: :delete, class: 'navbar-link' %>
          <% else %>
            <%= link_to "Sign Up", new_user_registration_path, class: 'navbar-link' %> -
            <%= link_to "Sign In", new_user_session_path, class: 'navbar-link'  %>
          <% end %>
        </div>
      </ul>
      <div class="flash">
        <% if flash[:notice] %>
          <div class="alert alert-success">
            <button type="button" class="close" data-dismiss="alert">&times;</button>
            <%= flash[:notice] %>
          </div>
        <% elsif flash[:error] %>
          <div class="alert alert-danger">
            <button type="button" class="close" data-dismiss="alert">&times;</button>
            <%= flash[:error] %>
          </div>
        <% elsif flash[:alert] %>
          <div class="alert alert-warning">
            <button type="button" class="close" data-dismiss="alert">&times;</button>
            <%= flash[:alert] %>
          </div>
        <% end %>
      </div>
      <%= yield %>
    </div>
  </body>
</html>

app/views/likes/_like.html.erb
<% if policy(Like.new).create? %>    
    <div class="like-div">
      <% if like = current_user.liked(bookmark) %>
        <%= link_to [bookmark, like], remote: true, class: 'btn btn-danger', id: "#{bookmark.id}-unlike", method: :delete do %>
          <i class="glyphicon glyphicon-star-empty"> </i>&nbsp; Unlike
        <% end %>
      <% else %>
        <%= link_to [bookmark, Like.new], remote: true, class: 'btn btn-primary', id: "#{bookmark.id}-like", method: :post do %>
          <i class="glyphicon glyphicon-star"> </i>&nbsp; Like
        <% end %>
      <% end %>
    </div>
<% end %>

app/views/likes/create.js.erb
<% if @like.valid? %>
    $('#' + <%= @bookmark.id %> + '-like').parent().html("<%= escape_javascript(render 'likes/like', bookmark: @bookmark) %>");
<% else %>
    $('.flash').prepend("<div class='alert alert-danger'><button type='button' class='close' data-dismiss='alert'>&times;</button><%= flash[:error] %></div>");
<% end %>

app/views/likes/destroy.js.erb
<% if @like.destroyed? %>
    $('#' + <%= @bookmark.id %> + '-unlike').parent().html("<%= escape_javascript(render 'likes/like', bookmark: @bookmark) %>");
<% else %>
    $('.flash').prepend("<div class='alert alert-danger'><button type='button' class='close' data-dismiss='alert'>&times;</button><%= flash[:error] %></div>");
<% end %>

app/views/topics/_form.html.erb
<%= form_for topic, remote: true do |f| %>
    <div class="form-group">
        <%= f.label :title %>
        <%= f.text_field :title, class: "form-control", placeholder: "Enter topic title" %>        
    </div>
    <div class="form-group">
        <%= f.submit "Add Topic", class: "btn btn-success" %>
    </div>
<% end %>

app/views/topics/_topic.html.erb
<div class="panel-heading">
    <h3 class="panel-title"><%= link_to "##{topic.title}", topic %>
        <% if policy(topic).destroy? %>
            <%= link_to topic, method: :delete, remote: true, title: "Delete topic", data: {confirm: "Do you want to delete #{topic.title}?"} do %>
                <i class="glyphicon glyphicon-remove pull-right" style="color:red"></i>
            <% end %>
        <% end %>
    </h3>
</div>

app/views/topics/create.js.erb
var flash = $('.flash');
var form = $("#topic-form");
<% if @topic.valid? %>
    $("#topic-list").append("<div class='panel panel-default' id=<%="#{@topic.id}-panel"%>></div>");
    var panel = $("#" + <%=@topic.id%> + "-panel");
    panel.append("<%= escape_javascript(render(@topic)) %>");
    panel.append("<div class='panel-body'></div>");
    flash.prepend("<div class='alert alert-success'><button type='button' class='close' data-dismiss='alert'>&times;</button><%= flash[:notice] %></div>");
    form.html("<%= escape_javascript(render 'topics/form', topic: @new_topic) %>");
    form.fadeOut();
<% else %>
    flash.prepend("<div class='alert alert-danger'><button type='button' class='close' data-dismiss='alert'>&times;</button><%= flash[:error] %></div>");
    form.html("<%= escape_javascript(render 'topics/form', topic: @topic) %>");
<% end %>
$('.alert').delay(5000).fadeOut();

app/views/topics/destroy.js.erb
<% if @topic.destroyed? %>
    $('#' + <%= @topic.id %> + '-panel').hide();
<% else %>
    $('.flash').prepend("<div class='alert alert-danger'><button type='button' class='close' data-dismiss='alert'>&times;</button><%= flash[:error] %></div>");
<% end %>

app/views/topics/edit.html.erb
<h1>Topics#edit</h1>
<p>Find me in app/views/topics/edit.html.erb</p>

app/views/topics/index.html.erb
<div class="row">
    <div class="col-md-10 col-md-offset-1 text-center page-header">
        <h1>All Blocmarks<% if policy(Topic).create? %><a><span class='glyphicon glyphicon-plus pull-right' id="add-icon" title="Add Topic"></span></a><% end %></h1>
    </div>
    <div class="col-md-10 col-md-offset-1" id="topic-list">
        <div id="topic-form">
            <%= render 'form', topic: Topic.new %>
        </div>
        <% @topics.each do |topic| %>
            <div class="panel panel-default" id=<%="#{topic.id}-panel" %>>
                <%= render topic %>
                <div class="panel-body">
                    <%= render partial: "bookmarks/bookmark", collection: topic.bookmarks %>
                </div>
            </div>
        <% end %>
    </div>
</div>



<script async src="//cdn.embedly.com/widgets/platform.js" charset="UTF-8"></script>

app/views/topics/show.html.erb
<div class="page-header">
    <h1 class="text-center"><%= "##{@topic.title}" %></h1>
</div>

<div class="row">
    <%= render partial: '/bookmarks/bookmark', collection: @topic.bookmarks, locals: {obj: "col-md-4" } %>
</div>

<script src="https://cdn.embed.ly/jquery.embedly-3.1.1.min.js" type="text/javascript"></script>
<script async src="//cdn.embedly.com/widgets/platform.js" charset="UTF-8"></script>

app/views/users/show.html.erb
<div class="row">
    <div class="col-md-10 col-md-offset-1 text-center page-header">
        <h1><%= show_name(@user) %>Blocmarks Page</h1>
    </div>
    <div class="col-md-10 col-md-offset-1 text-center">
        <h2><%= show_name(@user) %>Blocmarks</h2>
    </div>    
    <div class="col-md-10 col-md-offset-1">
        <% @user_bookmarks.each do |topic| %>
            <div class="panel panel-default" id=<%="#{topic.first.id}-panel" %>>
                <%= render topic.first %>
                <div class="panel-body">
                    <%= render partial: "bookmarks/bookmark", collection: topic.last %>
                </div>
            </div>
        <% end %>
    </div>
    <div class="col-md-10 col-md-offset-1 text-center">
        <h2><%= show_name(@user) %>Liked Blocmarks</h2>
    </div>    
    <div class="col-md-10 col-md-offset-1">
        <% @liked_bookmarks.each do |topic| %>
            <div class="panel panel-default" id=<%="#{topic.first.id}-panel" %>>
                <%= render topic.first %>
                <div class="panel-body">
                    <%= render partial: "bookmarks/bookmark", collection: topic.last %>
                </div>
            </div>
        <% end %>
    </div>
</div>

<script async src="//cdn.embedly.com/widgets/platform.js" charset="UTF-8"></script>

app/views/welcome/home.html.erb
<br>
<div class="jumbotron">
    <h1>Blocmarks:</h1>
    <p>Not your grandaddy's bookmark manager.</p>
    <p>Send in what you want to save!</p>
</div>